# --------------------------------------
# Configuración común (todos los perfiles)
# --------------------------------------
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Actuator: endpoints expuestos
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env

# SpringDoc: Swagger UI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# --------------------------------------
# Perfil de desarrollo
# --------------------------------------
---
spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
server:
  port: 8080
logging:
  level:
    root: INFO

# --------------------------------------
# Perfil de producción
# --------------------------------------
---
spring:
  config:
    activate:
      on-profile: prod
  h2:
    console:
      enabled: false
server:
  port: 8081
logging:
  level:
    root: WARN

# mvn spring-boot:run -Dspring-boot.run.profiles=dev
# mvn spring-boot:run -Dspring-boot.run.profiles=prod
